### ISSUE TITLE
Wrong?

### ISSUE THREAD

**Issue by Bandesss** [BigSpice/NorthStar-Mod-Manager-Ext-1#1]
![Screenshot_1](https://user-images.githubusercontent.com/50829319/147700588-68749c35-14ab-4705-b25c-ae0ae89678e7.jpg)
Hello this error comes to my?
Greet

**Comment by BigSpice** [comment]
All installs from 1.0.7 have been moved to the MSI file type, virus false flagging should not happen anymore.
