### ISSUE TITLE
[Suggestion] Format Mod Folders to Exclude full Dir name

### ISSUE THREAD

**Issue by SeamusMullan** [BigSpice/NorthStar-Mod-Manager-Ext-1#2]
Currently the list of mods is formatted with the full directory name and it's super hard to know what mods are what, eg;
`"D:\Program Files(x86)\Origin Games\Titanfall 2\R2Northstar\mods\{modname}"`

I think it would be a lot nice if everything before the `mods\` text was removed to increase readability!

**Comment by BigSpice** [comment]
Hi Seamus,
Fully Understand the Frustration :D!,
Working on a Fix as we speak, update should be out in a day or 2 :).

**Comment by BigSpice** [comment]
I will close this issue once you reply you are satisfied with the change, util then,
hold tight!, really sorry about that.

**Comment by BigSpice** [comment]
Hello @SeamusMullan ,
Happy New Year!,

I Hope the change is to your liking, please proceed to react on this message if you would like this issue closed.

**Comment by SeamusMullan** [comment]
Happy New Year!

That fix is perfect, can't wait to see the future of the manager!

**Comment by SeamusMullan** [comment]
.
