### ISSUE TITLE
Install Field text showing as white text on white background.

### ISSUE THREAD

**Issue by Vexalus** [BigSpice/NorthStar-Mod-Manager-Ext-1#5]
**Describe the bug**
The "Install Location" text field has white text on a white background.

**To Reproduce**
Wouldn't know, it always shows up like this for me no matter what.

**Expected behavior**
I'd expect for the text to be black like how it's shown in the readme screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/53546918/150303330-fdd9cd3f-a52d-4b2f-baf6-388e8a1a0b97.png)
![image](https://user-images.githubusercontent.com/53546918/150303344-02681c2e-051a-49ae-8792-8aca7ad2473c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
N/A

**Comment by BigSpice** [comment]
Hi Vexalus,
I belive i have found the reason for the bug, and will be pusing the fix along with 1.1.6.
I hope that is fine.

-Juicy

**Comment by Vexalus** [comment]
Alright. Sounds good.
